default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_bucket_name: <%= ENV["s3_bucket_name"] %>
  aws_region: <%= ENV["aws_region"] %>
  aws_access_key_id: <%= ENV["aws_access_key_id"] %>
  aws_secret_access_key: <%= ENV["aws_secret_access_key"] %>

development:
  <<: *default

production:
  <<: *default

test:
  secret_key_base: aaf163f30ca28568c98accd19e4b6e85113f051f5fa4b1abca1a49fc6c8606fb58af0174414be488a29a5670ddd93e66382eb65c229fec79352a5700ffd04d86
